n1 = float(input('Digite o primeiro numero: '))
n2 = float(input('Digite o segundo numero: '))
soma = int(n1 + n2)
#print('A soma entre', n1, 'e', n2, ',' 'vale:',soma)
print('A soma entre {} e {}, vale: {}'.format(n1, n2, soma))
